name: Deploy website to Hostinger
on:
  # workflow_dispatch: # Allow manual run from Github
  push:
    branches: [ main ] 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install and Build
      run: |
        npm install
        npm run build
        

    - name: 📂 Sync files with FTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /  # Root of the restricted FTP account
        dangerous-clean-slate: true